### ISSUE TITLE
Coloring does not work in `test.sh`

### ISSUE THREAD

**Issue by uloco** [osendott/custom_cursor_testing#1]
Just tested the script and the coloring does not work properly. I do always get the default styling no matter what I choose (light dark is also not working).

Also I get a lot of `Error reading config file!` errors at the end of the script. Perhaps this is the hint...

**Comment by osendott** [comment]
yeah it's all kinda screwed up at this point, it's due to stitching together parts of the old script into the new dialogs I believe. I think it's too much anyway. A lot of work for little gain. Probably best to rever to the old script, which as you pointed out, was basically finished.

**Comment by osendott** [comment]
All issues should be resolved. Dark/Light works, select color works, use custom color works, .png generation works, generate cursors works, installation works, cleanup works.
