### ISSUE TITLE
`Run in Terminal` fails

### ISSUE THREAD

**Issue by uloco** [osendott/custom_cursor_testing#7]
Hey, I was just checkin' out the new version and found a bug.
If I start the script from a file manager like nemo and choose `Run in Terminal` in the dialog that shows up, the script starts fine but aborts after the second screen.
Try it out...

**Comment by osendott** [comment]
it works fine for me either way - openting terminal and running ./generate.sh or double clicking and selecting run in terminal.. (which btw thanks, I had completely forgotton to turn that option back on)

**Comment by uloco** [comment]
I'm currently testing on a virtual machine, perhaps this affects the behaviour. I'll try again, when I'm home.

**Comment by osendott** [comment]
Just getting back home from vacation after a 10+hr drive, I'm tried lol I'm going to take a nap and then get back to the script. I have an idea for how to install to the /usr/share/icons directory without breaking the current UI. I'll use dialog's password box to ask for the users sudo password, and pass that to the sudo command via STDIN. This will save from having to let sudo prompt for the password in the commandline (or using gksudo which the user may or may not have, and which isn't necessary)

**Comment by osendott** [comment]
I'm going to assume this is no longer a problem? It seems to work fine on my side. I'm going to close this issue, let me know if it's still a problem, I'll reopen.
